### ISSUE TITLE
bp网络无法收敛

### ISSUE THREAD

**Issue by xvrong** [GavinTechStudio/bpnn_with_cpp#1]
无法收敛

**Comment by GavinSun0921** [comment]
我这边本地测试是可以的哦，可以自行debug看一下std::vector<Sample> train_data中的数据对不对

**Comment by GavinSun0921** [comment]
> 无法收敛

我这边本地测试是可以的哦，可以自行debug看一下std::vector train_data中的数据对不对

**Comment by xvrong** [comment]
大佬，de了一下，数据正确的读了进来，应该不是读取的问题

**Comment by GavinSun0921** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/22230347/127342430-2ca8739a-f2d0-4893-924f-63104e35269f.png">
我在本地测试是可以收敛的啊

**Comment by xvrong** [comment]
![image](https://user-images.githubusercontent.com/59106049/127348614-3fdca167-891c-437d-976b-b438381a0b29.png)
我这边是这样子的

**Comment by GavinSun0921** [comment]
看上去整体预测效果还不错，能否在229行代码之前添加一行输出error_max，来观察每次迭代最大误差的变化趋势：
```C++
std::cout << "error_max in " << times + 1 << " times training : "error_max << std::end;

if (error_max < ::threshold) {
    std::cout << "Success with " << times + 1 << " times training." << std::endl;
    std::cout << "Maximum error: " << error_max << std::endl;
    break;
}
```

**Comment by GavinSun0921** [comment]
如果还是不行的话，建议在每次迭代过程中，输出整个神经网络中的所有delta值，包括所有权值weight的delta和偏置值bias的delta，从而观察这次训练的所有修正参数是否正确。

**Comment by xvrong** [comment]
试了一下 error_ma增大的，很稳定的一直在增大
error_max in 1 times training : 0.156033
最后
error_max in 1000000 times training : 0.497556
我在想是不是代码中正负号出现了问题

**Comment by GavinSun0921** [comment]
这我就不清楚了，我直接运行这上面的代码也是可以收敛的，所有的delta产生都是按照理论推导得到的公式写的，正负号不会出错

**Comment by GavinSun0921** [comment]
GitHub上bpnn.cpp代码在我本地的多次测试都是可以收敛的：
```
Success with 319821 times training.
Maximum error: 9.99999e-05
0.111 0.112 0.00970223 
0.001 0.999 0.999995 
0.123 0.345 0.999979 
0.123 0.456 0.999993 
0.123 0.789 0.999995 
0.234 0.567 0.999993 
0.234 0.678 0.999995 
0.387 0.401 0.0252321 
0.616 0.717 0.985532 
0.701 0.919 0.999981
```

**Comment by GavinSun0921** [comment]
介于你的最终预测结果比较良好，并且你的error_max还一直处于增加，可以检查一下你的error_max在每轮迭代开始时是否将其重置为0。

**Comment by xvrong** [comment]
大佬，我找到问题了，可能是我使用linux的原因，我下载后traindata里多了一行空行，读取数据莫名多了一组1 0 0
![image](https://user-images.githubusercontent.com/59106049/127357527-7d1b0678-60c6-40cf-b170-338b67c74a2c.png)
就收敛不了了... 
把空行删去 就收敛了...

**Comment by xvrong** [comment]
![image](https://user-images.githubusercontent.com/59106049/127359404-77cde9be-547e-46ff-8ab2-458877e70bc7.png)
测试了一下 windows下也有这个问题，项目clone下来后，train_data.txt最后会多出来一行空行， 最后有空行的话，就会莫名其妙多出一组数据

**Comment by GavinSun0921** [comment]
OK，解决就好
